const styles = {
  container: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    marginTop: "25px",
  },
  h1: {
    fontFamily: "'Poppins', 'sans-serif'",
    fontWeight: "700",
  },
  main: {
    position: "relative",
    width: "23%",
    backgroundColor: "rgba(244, 245, 247, 1)",
  },
  item: {
    display: "flex",
    justifyContent: "space-around",
    rowGap: "15px",
    flexWrap: "wrap",
  },
  btn: {
    marginTop: "15px",
    marginBottom: "15px",
    padding: "15px",
    border: "1px solid rgba(184, 142, 47, 1)",
    color: "rgba(184, 142, 47, 1)",
  },
  img: {
    height: "250px",
    width: "100%",
  },
  h3: {
    color: "rgba(58, 58, 58, 1)",
    fontSize: "24px",
    fontFamily: "'Poppins', 'sans-serif'",
    fontWeight: "600",
  },
  p: {
    color: "rgba(137, 137, 137, 1)",
    fontFamily: "'Poppins', 'sans-serif'",
    fontWeight: "500",
  },
  content: {
    marginTop: "7px",
    marginLeft: "10px",
    display: "flex",
    flexDirection: "column",
  },
  price: {
    display: "flex",
    alignItems: "center",
    gap: "20px",
    p: {
      color: "rgba(58, 58, 58, 1)",
      fontFamily: "'Poppins', 'sans-serif'",
      fontWeight: "600",
      fontSize: "20px",
    },
    p1: {
      color: "rgba(176, 176, 176, 1)",
      fontFamily: "'Poppins', 'sans-serif'",
      fontWeight: "400",
      fontSize: "16px",
      textDecoration: "line-through",
    },
  },
  circle: {
    position: "absolute",
    border: "0.5px solid transparent",
    borderRadius: "50%",
    height: "48px",
    width: "48px",
    top: "10px",
    right: "10px",
    padding: "11.5px",
    color: "white",
    textAlign: "center",
  },
  hoverBox: {
    position: "absolute",
    top: "0",
    height: "100%",
    width: "100%",
    transition: "1s ease-in-out",
    boxSizing: "border-box",
    backgroundColor: "rgba(58, 58, 58, 1)",
    opacity: "80%",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
  },
  button: {
    backgroundColor: "rgba(255, 255, 255, 1)",
    color: "rgba(184, 142, 47, 1)",
    fontFamily: "'Poppins', 'sans-serif'",
    fontWeight: "600",
    width: "202px",
    height: "48px",
  },
  icons: {
    display: "flex",
    gap: "15px",
    p: {
      color: "rgba(255, 255, 255, 1)",
      fontFamily: "'Poppins', 'sans-serif'",
      fontWeight: "600",
    },
  },
};
export default styles;
