import data from "../../assets/data.js";
let index = 0;
const products = [
  {
    id: 0,
    data: data[index++],
    discount: 50,
    price: 5000,
    newItem: true,
    quantity: 1,
  },
  {
    id: 1,
    data: data[index++],
    discount: 30,
    price: 10000,
    newItem: true,
    quantity: 1,
  },
  {
    id: 2,
    data: data[index++],
    discount: 10,
    price: 7000,
    newItem: false,
    quantity: 1,
  },
  {
    id: 3,
    data: data[index++],
    discount: 50,
    price: 2000,
    newItem: false,
    quantity: 1,
  },
  {
    id: 4,
    data: data[index++],
    discount: 25,
    price: 7500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 5,
    data: data[index++],
    discount: 20,
    price: 2500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 6,
    data: data[index++],
    discount: 15,
    price: 2500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 7,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 8,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 9,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 10,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 11,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 12,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 13,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 14,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 15,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
    
  },
  {
    id: 16,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 17,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 18,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
    
  },
  {
    id: 19,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 20,
    data: data[index++],
    discount: 50,
    price: 5000,
    newItem: true,
    quantity: 1,
  },
  {
    id: 21,
    data: data[index++],
    discount: 30,
    price: 10000,
    newItem: false,
    quantity: 1,
  },
  {
    id: 22,
    data: data[index++],
    discount: 10,
    price: 7000,
    newItem: false,
    quantity: 1,
  },
  {
    id: 23,
    data: data[index++],
    discount: 50,
    price: 2000,
    newItem: true,
    quantity: 1,
  },
  {
    id: 24,
    data: data[index++],
    discount: 25,
    price: 7500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 25,
    data: data[index++],
    discount: 20,
    price: 2500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 26,
    data: data[index++],
    discount: 15,
    price: 2500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 27,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 28,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 29,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 30,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 31,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 32,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 33,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 34,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 35,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: true,
    quantity: 1,
  },
  {
    id: 36,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 37,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 38,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
  {
    id: 39,
    data: data[index++],
    discount: 10,
    price: 1500,
    newItem: false,
    quantity: 1,
  },
];
export default products;
